import { jsPDF } from "jspdf";
import type { EvaluationResponse, GapAnalysisEntry } from "../api/types";
import { recommendationLabel } from "./recommendationLabels";

interface MergedRow {
  id: string;
  status: string;
  heading: string;
  mandatory: boolean | null;
  risk_level: string | null;
  matching_confidence: number | null;
  supporting_evidence?: string | null;
}

// Architecture debate Phase 6 -- executive-facing labels over the
// backend's own remediation_summary.qualification/bid_readiness values.
// Same copy as Evaluation.tsx's QUALIFICATION_COPY/READINESS_COPY;
// duplicated here rather than imported because pdfReport.ts is
// dynamically imported standalone from Evaluation.tsx (see its own
// handleDownloadPdf) and this keeps it a self-contained module with no
// React dependency.
const QUALIFICATION_COPY: Record<string, string> = { pass: "Pass", conditional: "Conditional", fail: "Fail" };
const READINESS_COPY: Record<string, string> = { ready: "Ready", action_required: "Action Required", blocked: "Blocked" };

interface ReportMeta {
  companyName: string;
  missionType: string;
  missionId: string;
}

const BRAND_PRIMARY: [number, number, number] = [99, 102, 241]; // #6366F1
const INK: [number, number, number] = [30, 32, 44];
const MUTED: [number, number, number] = [100, 116, 139]; // Dark Slate #64748B
const WARNING: [number, number, number] = [180, 130, 12]; // Amber, for administrator-override disclosure

const PAGE_WIDTH = 210;
const MARGIN = 18;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const PAGE_HEIGHT = 297;
const FOOTER_Y = PAGE_HEIGHT - 12;

function pct(v: number | null) {
  return v == null ? "—" : `${Math.round(v * 100)}%`;
}

/**
 * Generates a real, professional PDF client-side (jsPDF) from data already
 * on the page -- no backend endpoint required. Replaces the earlier plain
 * .txt export.
 */
export function generateEvaluationPdf(data: EvaluationResponse, merged: MergedRow[], meta: ReportMeta) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = 0;

  const addFooter = () => {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setDrawColor(...MUTED);
      doc.setLineWidth(0.2);
      doc.line(MARGIN, FOOTER_Y - 4, PAGE_WIDTH - MARGIN, FOOTER_Y - 4);
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      doc.text("Generated by PRAMAAN — From Documents to Decisions.", MARGIN, FOOTER_Y);
      doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN, FOOTER_Y, { align: "right" });
    }
  };

  const ensureSpace = (needed: number) => {
    if (y + needed > FOOTER_Y - 10) {
      doc.addPage();
      y = MARGIN;
    }
  };

  const heading = (text: string) => {
    ensureSpace(12);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...INK);
    doc.text(text, MARGIN, y);
    y += 2;
    doc.setDrawColor(...BRAND_PRIMARY);
    doc.setLineWidth(0.6);
    doc.line(MARGIN, y, MARGIN + 14, y);
    y += 7;
  };

  // --- Header band ---
  doc.setFillColor(...BRAND_PRIMARY);
  doc.rect(0, 0, PAGE_WIDTH, 32, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("PRAMAAN", MARGIN, 13);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Tender Analysis Report", MARGIN, 20.5);
  doc.setFontSize(8.5);
  doc.setTextColor(255, 255, 255);
  doc.text("From Documents to Decisions.", MARGIN, 27);
  y = 42;

  // --- Executive summary meta table ---
  // Architecture debate Phase 6: Qualification / Bid Readiness / System
  // Coverage / Human Review rows are read directly from
  // data.remediation_summary -- the same backend-authoritative
  // classification the UI now renders, never re-derived from
  // gap_analysis here (see the PDF/UI parity requirement).
  const { recommendation, remediation_summary: remediation } = data;
  const metaRows: [string, string][] = [
    ["Company", meta.companyName || "—"],
    ["Mission", meta.missionType],
    ["Date", new Date(recommendation.generated_at).toLocaleString()],
    ["Recommendation", recommendationLabel(recommendation.recommendation_type)],
    ["Qualification", QUALIFICATION_COPY[remediation.qualification] ?? remediation.qualification],
    ["Bid Readiness", READINESS_COPY[remediation.bid_readiness] ?? remediation.bid_readiness],
    [
      "System Coverage",
      remediation.coverage_gaps.length === 0 ? "Complete" : `${remediation.coverage_gaps.length} gap(s)`,
    ],
    [
      "Human Review",
      remediation.human_review_items.length === 0 ? "None" : `${remediation.human_review_items.length} item(s)`,
    ],
    ["Risk Level", recommendation.risk_level ? recommendation.risk_level.toUpperCase() : "—"],
    ["Overall Confidence", pct(recommendation.overall_confidence)],
  ];

  doc.setFontSize(10);
  metaRows.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...MUTED);
    doc.text(`${label}:`, MARGIN, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...INK);
    doc.text(value, MARGIN + 42, y);
    y += 6;
  });
  y += 4;

  // --- Executive summary paragraph ---
  heading("Executive Summary");
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...INK);
  const summaryLines = doc.splitTextToSize(recommendation.executive_summary ?? "No summary available.", CONTENT_WIDTH);
  ensureSpace(summaryLines.length * 5 + 4);
  doc.text(summaryLines, MARGIN, y);
  y += summaryLines.length * 5 + 8;

  // --- Confidence breakdown ---
  heading("Confidence Breakdown");
  const confRows: [string, string][] = [
    ["Document Confidence", pct(recommendation.document_confidence)],
    ["Entity Confidence", pct(recommendation.entity_confidence)],
    ["Matching Confidence", pct(recommendation.matching_confidence)],
    ["Recommendation Confidence", pct(recommendation.recommendation_confidence)],
  ];
  doc.setFontSize(10);
  confRows.forEach(([label, value]) => {
    ensureSpace(6);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(label, MARGIN, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...INK);
    doc.text(value, MARGIN + 60, y);
    y += 6;
  });
  y += 4;

  // CONDITIONAL_GO must never appear as a vague standalone label -- same
  // hard requirement as the UI's breakdown block, same source data.
  if (recommendation.recommendation_type === "conditional_go") {
    heading("Conditional GO Breakdown");
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...INK);
    const breakdown = `Qualification: ${QUALIFICATION_COPY[remediation.qualification]}  ·  Bid Readiness: ${
      READINESS_COPY[remediation.bid_readiness]
    }  ·  Blocked: ${remediation.blocked_items.length}  ·  Action required: ${
      remediation.action_required_items.length
    }  ·  Coverage gaps: ${remediation.coverage_gaps.length}  ·  Human review: ${remediation.human_review_items.length}`;
    const lines = doc.splitTextToSize(breakdown, CONTENT_WIDTH);
    ensureSpace(lines.length * 5 + 4);
    doc.text(lines, MARGIN, y);
    y += lines.length * 5 + 8;
  }

  // REVIEW must never appear unexplained either -- architecture debate
  // Phase 6 (REVIEW-explainability gap). Same source data and same
  // reasoning as Evaluation.tsx's "Why REVIEW" box: REVIEW only fires
  // when qualification is PASS and bid_readiness is READY, so the one
  // backend-authoritative explanation left is optional_capability_gaps.
  if (recommendation.recommendation_type === "review") {
    heading("Why REVIEW");
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...INK);
    const whyReview =
      remediation.optional_capability_gaps.length > 0
        ? `Qualification and bid readiness are both clean, but ${remediation.optional_capability_gaps.length} non-mandatory capability item(s) are not currently met -- see Optional Capability Gaps below.`
        : "This reflects a volume of optional items across this evaluation -- see the Compliance Matrix for the full detail.";
    const lines = doc.splitTextToSize(whyReview, CONTENT_WIDTH);
    ensureSpace(lines.length * 5 + 4);
    doc.text(lines, MARGIN, y);
    y += lines.length * 5 + 8;
  }

  // --- Remediation sections ---
  // Architecture debate Phase 6: each section below is exactly one
  // remediation_summary array, rendered in the same order and with the
  // same framing as Evaluation.tsx's Analysis tab. Counts and membership
  // come only from remediation_summary -- never independently filtered
  // from gap_analysis or compliance_matrix here (the PDF/UI parity
  // requirement: if the UI says "Qualification gaps: 4" this PDF must
  // derive the same 4 from the same field, not recompute
  // `mandatory && not_met`).
  const renderGapSection = (title: string, items: GapAnalysisEntry[], emptyCopy: string, note: string) => {
    heading(`${title} — ${items.length} Item(s)`);
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(...MUTED);
    const noteLines = doc.splitTextToSize(note, CONTENT_WIDTH);
    ensureSpace(noteLines.length * 4.2 + 3);
    doc.text(noteLines, MARGIN, y);
    y += noteLines.length * 4.2 + 4;

    if (items.length === 0) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...INK);
      ensureSpace(6);
      doc.text(emptyCopy, MARGIN, y);
      y += 8;
      return;
    }

    items.forEach((g, i) => {
      const lines = doc.splitTextToSize(`${i + 1}. ${g.description ?? "Requirement"}`, CONTENT_WIDTH);
      ensureSpace(lines.length * 5 + 4);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...INK);
      doc.text(lines, MARGIN, y);
      y += lines.length * 5 + 1;
      if (g.unsupported_domains.length > 0) {
        ensureSpace(5);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(...MUTED);
        doc.text(`Unsupported domain(s): ${g.unsupported_domains.join(", ")}`, MARGIN + 4, y);
        y += 5;
      }
      if (g.reason) {
        const reasonLines = doc.splitTextToSize(g.reason, CONTENT_WIDTH - 4);
        ensureSpace(reasonLines.length * 4.5 + 3);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(...MUTED);
        doc.text(reasonLines, MARGIN + 4, y);
        y += reasonLines.length * 4.5 + 3;
      }
      // Qualification override disclosure -- never let a PDF report an
      // overridden gap the same way it reports a genuinely-resolved one.
      // Mirrors the ActionCenter/Evaluation.tsx override panel: always
      // shows who, when, and the mandatory audit note, printed in amber
      // to visually distinguish it from an ordinary reason line.
      if (g.overridden) {
        const overrideHeader = `Administrator override -- ${g.overridden_by_name ?? "an administrator"}${
          g.overridden_at ? ` · ${new Date(g.overridden_at).toLocaleDateString()}` : ""
        }`;
        ensureSpace(5);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(...WARNING);
        doc.text(overrideHeader, MARGIN + 4, y);
        y += 4.5;
        if (g.override_note) {
          const overrideLines = doc.splitTextToSize(`"${g.override_note}"`, CONTENT_WIDTH - 4);
          ensureSpace(overrideLines.length * 4.5 + 3);
          doc.setFont("helvetica", "italic");
          doc.setFontSize(9);
          doc.setTextColor(...WARNING);
          doc.text(overrideLines, MARGIN + 4, y);
          y += overrideLines.length * 4.5 + 3;
        } else {
          y += 2;
        }
      }
    });
    y += 4;
  };

  renderGapSection(
    "Qualification Gaps",
    remediation.qualification_gaps,
    "No genuine capability gaps -- every certification/experience/personnel/equipment claim checked out.",
    "Capability requirements the company does not currently satisfy. Items marked below as an administrator override have been permitted to pass without evidence, on record."
  );
  renderGapSection(
    "Bid Readiness — Blocked",
    remediation.blocked_items,
    "Nothing is blocking submission.",
    "Mandatory submission items (e.g. EMD, DSC, portal registration, declarations) still unresolved."
  );
  renderGapSection(
    "Bid Readiness — Action Required",
    remediation.action_required_items,
    "No outstanding bid-preparation actions.",
    "Routine bid mechanics and future contractual commitments the team needs to act on -- not capability gaps."
  );
  renderGapSection(
    "System Coverage Gaps",
    remediation.coverage_gaps,
    "System coverage is complete -- PRAMAAN could evaluate every requirement.",
    "PRAMAAN could not fully evaluate these requirements yet. This reflects a system limitation, not a confirmed company deficiency."
  );
  renderGapSection(
    "Human Review",
    remediation.human_review_items,
    "Nothing needs human review.",
    "Ambiguous evidence on genuine capability requirements -- distinct from a confirmed failure or a coverage limitation."
  );
  renderGapSection(
    "Optional Capability Gaps",
    remediation.optional_capability_gaps,
    "No outstanding optional capability items.",
    "Non-mandatory capability requirements not currently met -- not a qualification risk, but a factor in the overall recommendation (see Why REVIEW above, when applicable)."
  );

  // --- Full compliance matrix (unchanged in structure -- remains the
  // authoritative detail ledger; the sections above are a summary, not a
  // replacement) ---
  heading(`Compliance Matrix — ${merged.length} Requirement(s)`);
  doc.setFontSize(9);
  merged.forEach((row, i) => {
    const statusLabel = `[${row.status.toUpperCase().replace(/_/g, " ")}]`;
    const lines = doc.splitTextToSize(`${i + 1}. ${statusLabel} ${row.heading}`, CONTENT_WIDTH);
    ensureSpace(lines.length * 4.6 + 2);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...INK);
    doc.text(lines, MARGIN, y);
    y += lines.length * 4.6 + 2;
    if (row.supporting_evidence) {
      const evidenceLines = doc.splitTextToSize(`Evidence: ${row.supporting_evidence}`, CONTENT_WIDTH - 4);
      ensureSpace(evidenceLines.length * 4 + 2);
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      doc.text(evidenceLines, MARGIN + 4, y);
      y += evidenceLines.length * 4 + 2;
      doc.setFontSize(9);
      doc.setTextColor(...INK);
    }
  });

  addFooter();
  doc.save(`pramaan-report-${meta.missionId.slice(0, 8)}.pdf`);
}
